language: generic
sudo: required
before_script:
- sudo apt-get remove --purge docker-engine
- curl -fsSL https://get.docker.com/ | sh
- curl -L https://github.com/opspec-io/opctl/releases/download/0.1.14/opctl-linux.tgz | sudo tar -xzv -C /usr/local/bin
services:
- docker
script:
- opctl run release
env:
  global:
  - secure: zxncC+fNKPoYSLP4meG2i0e4nAWs89jlfvpqGPWuzK5w3FT4k61MMsWgXAUG+5mVVIkeMCLKhYN98mfOJY9Ia/uigl+lrhXxzb4WWNNzd5RF01iT9nvzMg4LmdOrc9t9s0D0dC/FOY/E1L751gLGKmJtBGcnaT/Hmc2VvYXk0cRNbm+rsXil8gaQM9ZsnVi7oyjesqjxReqx9bbk1+XKCuKNQlRtzOL5vItrjjKo9jrP742ZpIaV0Ptc0pFvUsG0fZXkFU4R7JQTeqMFsC/MFtSyXI8REb0ZnAmgh2/nV8K04h4bOhIzQVg5BA+A/xOpkRCbAiv1OkXmAQNOJ54ctRCrTK6weNpqT54Hmbenp4D17G0S+Q0UPlR/KzL1kyftaMcfNsi9rsrr+2b9y2kZ1ymR8XSFlaaZJnb4bXnL7Zd8Hy1Ni+UVaAn2TtB+9ClyyLfAnelJGB0Kq7Cif0GLk0aNEGH/W4ngeCdNU8SuaXnnYp4FgUvF9lFkCsySmD7zoo0Ucgm9SQ/NvNYWEmy9xM1jhvhbNLjUMJp7In3kdpO8Yo8Zmr07+jfKlTyZ4lnA4mzPVSHs8nwRUcQyQoPAeDnvKNczDzDl5emAvXNd4K7YSeglDa7IdkTvVEZf8RA45QM9YJOYXNB9voqp70f5KS+NyLnrXCtIVkY7P+O9Mpw=
  - secure: dZRhf7aNiUHoZSHOgIewA0zb7GPDiLzq4u1PdJmuDb/cGWB3DBa0llnBLebsBuWC0WOYXyHCljIFzkxi1wYDzYafml/OpO7vNiSN0zvBKdvtThO+oJOYC24HH1zbsZAvKVoAk1R+NFgiZNiaPSGrdw41rEkO4qZnR/E1eAPNPbBXXErS8SjfwmYh0RG+aUyDRW3rz83XMztSvRdbs8yATGW/ZJWJQqVtbIltO6qoMcogbYlpFMk/UQfWVKGh3otlSnCLTfxaXTFRmhFieU3P3tzIem9xzn8I/JVY/SgSnMQv6tAX63ATEt9QNzXOgk9Uj5jYcQQOpaZ/ppEVuzWldPa439DDZxCK4dyWetNo7c5Eq27/zmzouDEHkkdoyMdmHHa/cULkDFkNDK3Y7vrNctpQNJ/O+UYiLF3Bca0qwz0ggWCUef7sw4ZMCQ2BXIEC/t0hqS4+3FV8egIgj+A+P4nTLs7C4MbWfsFDjZjjjcyDZs4mUIoIdpVu/P1wU2Aga32kTmd4yoRdteTOdKBnvsjYLy40IjlXPk2xadPAoWSvmykczBRzyA5sVyg3ZCja7D8EU3U679Lg0Z/017dkMJuJSVME73AnRapNVs36CZUrvswhNZjmzExJESwgTVZn5aQBJsyhai8oMe3LxJGrcc7A5K6YPRM2Nqo2luafU6U=
